In [1]:
import pandas as pd

In [2]:
pwd

'e:\\Udemy\\ML_DataScience\\pycrash'

In [3]:
ls

 Volume in drive E has no label.
 Volume Serial Number is 0CCE-118E

 Directory of e:\Udemy\ML_DataScience\pycrash

08/29/2021  05:12 PM    <DIR>          .
08/29/2021  05:12 PM    <DIR>          ..
07/23/2021  12:57 AM             8,308 crash_python.ipynb
07/12/2021  12:10 AM            27,815 numpy_exm.ipynb
07/23/2021  12:12 AM           143,794 pandas_data_frame.ipynb
08/29/2021  05:12 PM                 0 pandas_data_input_output.ipynb
08/26/2021  06:39 PM             4,961 pandas_date_time_method.ipynb
07/29/2021  12:17 AM            36,719 pandas_group_by_op.ipynb
08/25/2021  04:16 PM            11,856 pandas_merging_combine.ipynb
07/23/2021  01:56 AM            72,519 pandas_methos_statistical.ipynb
07/28/2021  11:45 PM            23,255 pandas_missing_data.ipynb
07/16/2021  12:56 AM             4,393 pandas_series.ipynb
08/25/2021  06:02 PM             9,711 pandas_text_data_manage.ipynb
07/07/2021  10:07 PM                 9 README.md
              12 File(s)        343,340 bytes
               2 Dir(s)  52,111,216,640 bytes free

In [4]:
import os

In [5]:
os.getcwd()

'e:\\Udemy\\ML_DataScience\\pycrash'

In [10]:
df = pd.read_csv('D:/Download/UNZIP_FOR_NOTEBOOKS_FINAL/03-Pandas/hotel_booking_data.csv', index_col=0)

In [9]:
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,Transient,0.00,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,Transient,0.00,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,Transient,75.00,0,0,Check-Out,2015-07-02,Rebecca Parker,Rebecca_Parker@comcast.net,652-885-2745,************3734
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,Transient,75.00,0,0,Check-Out,2015-07-02,Laura Murray,Laura_M@gmail.com,364-656-8427,************5677
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,Transient,98.00,0,1,Check-Out,2015-07-03,Linda Hines,LHines@verizon.com,713-226-5883,************5498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,Transient,96.14,0,0,Check-Out,2017-09-06,Claudia Johnson,Claudia.J@yahoo.com,403-092-5582,************8647
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,Transient,225.43,0,2,Check-Out,2017-09-07,Wesley Aguilar,WAguilar@xfinity.com,238-763-0612,************4333
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,Transient,157.71,0,4,Check-Out,2017-09-07,Mary Morales,Mary_Morales@hotmail.com,395-518-4100,************1821
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,Transient,104.40,0,0,Check-Out,2017-09-07,Caroline Conley MD,MD_Caroline@comcast.net,531-528-1017,************7860
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,Transient,151.20,0,2,Check-Out,2017-09-07,Ariana Michael,Ariana_M@xfinity.com,422-804-6403,************4482